# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: interview.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'interview.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finterview.proto\x12\tinterview\"o\n\x10\x43\x61ndidateMessage\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x17\n\x0ftext_transcript\x18\x02 \x01(\t\x12\x15\n\rcode_snapshot\x18\x03 \x01(\t\x12\x17\n\x0fis_final_answer\x18\x04 \x01(\x08\"^\n\nAiResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\ntext_chunk\x18\x02 \x01(\t\x12\x13\n\x0b\x61udio_chunk\x18\x03 \x01(\x0c\x12\x13\n\x0bis_complete\x18\x04 \x01(\x08\x32]\n\x10InterviewService\x12I\n\x0fStreamInterview\x12\x1b.interview.CandidateMessage\x1a\x15.interview.AiResponse(\x01\x30\x01\x42\x16Z\x14./proto;interview_v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interview_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\024./proto;interview_v1'
  _globals['_CANDIDATEMESSAGE']._serialized_start=30
  _globals['_CANDIDATEMESSAGE']._serialized_end=141
  _globals['_AIRESPONSE']._serialized_start=143
  _globals['_AIRESPONSE']._serialized_end=237
  _globals['_INTERVIEWSERVICE']._serialized_start=239
  _globals['_INTERVIEWSERVICE']._serialized_end=332
# @@protoc_insertion_point(module_scope)
