package config

import (
	"log"
	"os"
	"strconv"
	"time"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

// DB is the global database instance we use across the app.
var DB *gorm.DB

// ConnectDB initializes the connection pool to Postgres (Supabase).
//
// The pool settings are not cosmetic. GORM's default is an unlimited number
// of open connections, and Supabase's pooler will start refusing them long
// before Go stops opening them — so under real concurrency the failure mode
// is "too many clients already" rather than requests politely queueing.
func ConnectDB() {
	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		log.Fatal("DATABASE_URL environment variable is not set")
	}

	gormLevel := logger.Warn
	if os.Getenv("APP_ENV") == "production" {
		// Never log statements in production: they carry user data and repo
		// names into whatever aggregates the container's stdout.
		gormLevel = logger.Error
	}

	var err error
	DB, err = gorm.Open(postgres.Open(dsn), &gorm.Config{
		Logger: logger.Default.LogMode(gormLevel),
		// Our IDs are generated by Postgres defaults; skipping the default
		// transaction wrapper on single writes is a straight win.
		SkipDefaultTransaction: true,
	})
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}

	sqlDB, err := DB.DB()
	if err != nil {
		log.Fatalf("Failed to access the underlying connection pool: %v", err)
	}
	sqlDB.SetMaxOpenConns(envInt("DB_MAX_OPEN_CONNS", 25))
	sqlDB.SetMaxIdleConns(envInt("DB_MAX_IDLE_CONNS", 5))
	// Poolers recycle server-side connections; holding one longer than they
	// do produces "unexpected EOF" on an otherwise healthy query.
	sqlDB.SetConnMaxLifetime(30 * time.Minute)
	sqlDB.SetConnMaxIdleTime(5 * time.Minute)

	if err := sqlDB.Ping(); err != nil {
		log.Fatalf("Database is unreachable: %v", err)
	}

	log.Println("Database connected successfully via GORM!")
}

func envInt(name string, fallback int) int {
	if raw := os.Getenv(name); raw != "" {
		if n, err := strconv.Atoi(raw); err == nil && n > 0 {
			return n
		}
	}
	return fallback
}
