// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.2
// source: interview.proto

package interview_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sent from Go -> Python
type CandidateMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TextTranscript string                 `protobuf:"bytes,2,opt,name=text_transcript,json=textTranscript,proto3" json:"text_transcript,omitempty"` // Real-time STT transcript from Deepgram
	CodeSnapshot   string                 `protobuf:"bytes,3,opt,name=code_snapshot,json=codeSnapshot,proto3" json:"code_snapshot,omitempty"`       // Current state of the Monaco editor
	IsFinalAnswer  bool                   `protobuf:"varint,4,opt,name=is_final_answer,json=isFinalAnswer,proto3" json:"is_final_answer,omitempty"` // True if the candidate clicked "Submit Response"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CandidateMessage) Reset() {
	*x = CandidateMessage{}
	mi := &file_interview_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateMessage) ProtoMessage() {}

func (x *CandidateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_interview_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateMessage.ProtoReflect.Descriptor instead.
func (*CandidateMessage) Descriptor() ([]byte, []int) {
	return file_interview_proto_rawDescGZIP(), []int{0}
}

func (x *CandidateMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CandidateMessage) GetTextTranscript() string {
	if x != nil {
		return x.TextTranscript
	}
	return ""
}

func (x *CandidateMessage) GetCodeSnapshot() string {
	if x != nil {
		return x.CodeSnapshot
	}
	return ""
}

func (x *CandidateMessage) GetIsFinalAnswer() bool {
	if x != nil {
		return x.IsFinalAnswer
	}
	return false
}

// Sent from Python -> Go
type AiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TextChunk     string                 `protobuf:"bytes,2,opt,name=text_chunk,json=textChunk,proto3" json:"text_chunk,omitempty"`     // Streaming LLM text chunk
	AudioChunk    []byte                 `protobuf:"bytes,3,opt,name=audio_chunk,json=audioChunk,proto3" json:"audio_chunk,omitempty"`  // Optional TTS audio chunk (Aura or ElevenLabs)
	IsComplete    bool                   `protobuf:"varint,4,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"` // True when the AI is done speaking for this turn
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiResponse) Reset() {
	*x = AiResponse{}
	mi := &file_interview_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiResponse) ProtoMessage() {}

func (x *AiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interview_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiResponse.ProtoReflect.Descriptor instead.
func (*AiResponse) Descriptor() ([]byte, []int) {
	return file_interview_proto_rawDescGZIP(), []int{1}
}

func (x *AiResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AiResponse) GetTextChunk() string {
	if x != nil {
		return x.TextChunk
	}
	return ""
}

func (x *AiResponse) GetAudioChunk() []byte {
	if x != nil {
		return x.AudioChunk
	}
	return nil
}

func (x *AiResponse) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

var File_interview_proto protoreflect.FileDescriptor

const file_interview_proto_rawDesc = "" +
	"\n" +
	"\x0finterview.proto\x12\tinterview\"\xa7\x01\n" +
	"\x10CandidateMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0ftext_transcript\x18\x02 \x01(\tR\x0etextTranscript\x12#\n" +
	"\rcode_snapshot\x18\x03 \x01(\tR\fcodeSnapshot\x12&\n" +
	"\x0fis_final_answer\x18\x04 \x01(\bR\risFinalAnswer\"\x8c\x01\n" +
	"\n" +
	"AiResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"text_chunk\x18\x02 \x01(\tR\ttextChunk\x12\x1f\n" +
	"\vaudio_chunk\x18\x03 \x01(\fR\n" +
	"audioChunk\x12\x1f\n" +
	"\vis_complete\x18\x04 \x01(\bR\n" +
	"isComplete2]\n" +
	"\x10InterviewService\x12I\n" +
	"\x0fStreamInterview\x12\x1b.interview.CandidateMessage\x1a\x15.interview.AiResponse(\x010\x01B\x16Z\x14./proto;interview_v1b\x06proto3"

var (
	file_interview_proto_rawDescOnce sync.Once
	file_interview_proto_rawDescData []byte
)

func file_interview_proto_rawDescGZIP() []byte {
	file_interview_proto_rawDescOnce.Do(func() {
		file_interview_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interview_proto_rawDesc), len(file_interview_proto_rawDesc)))
	})
	return file_interview_proto_rawDescData
}

var file_interview_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_interview_proto_goTypes = []any{
	(*CandidateMessage)(nil), // 0: interview.CandidateMessage
	(*AiResponse)(nil),       // 1: interview.AiResponse
}
var file_interview_proto_depIdxs = []int32{
	0, // 0: interview.InterviewService.StreamInterview:input_type -> interview.CandidateMessage
	1, // 1: interview.InterviewService.StreamInterview:output_type -> interview.AiResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_interview_proto_init() }
func file_interview_proto_init() {
	if File_interview_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interview_proto_rawDesc), len(file_interview_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interview_proto_goTypes,
		DependencyIndexes: file_interview_proto_depIdxs,
		MessageInfos:      file_interview_proto_msgTypes,
	}.Build()
	File_interview_proto = out.File
	file_interview_proto_goTypes = nil
	file_interview_proto_depIdxs = nil
}
